version: '2'
services:
  nginx:
    image: shippingdocker/nginx:latest
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  php:
    image: shippingdocker/php:1.2
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: project-name
      POSTGRES_DB: project-name
      POSTGRES_USER: project-name
    volumes:
     - data:/var/lib/postgres
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
