version: '2'
services:
  nginx:
    image: shippingdocker/nginx:1.2
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  php:
    image: shippingdocker/php:1.2
    volumes:
     - .:/var/www/html
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: postgres:latest
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: project-name
      POSTGRES_DB: project-name
      POSTGRES_USER: project-name
    volumes:
     - data:/var/lib/postgres
    networks:
     - appnet
  mail:
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
